[package]
name = "motiongfx_macro_utils"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
syn = "2.0"
quote = "1.0"
toml_edit = "0.22"

[lints]
workspace = true
