[package]
name = "motiongfx_bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
motiongfx_core = { path = "../motiongfx_core" }

bevy_ecs = "0.13"
bevy_app = "0.13"
bevy_math = "0.13"
bevy_transform = "0.13"
bevy_pbr = "0.13"
bevy_asset = "0.13"
bevy_render = "0.13"

[lints]
workspace = true
