[package]
name = "motiongfx_core"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_app = { version = "0.12", default-features = false }
bevy_ecs = { version = "0.12", default-features = false }
bevy_math = { version = "0.12", default-features = false }
bevy_render = { version = "0.12", default-features = false }
bevy_time = { version = "0.12", default-features = false }
bevy_utils = { version = "0.12", default-features = false }
bevy_vello_renderer = { git = "https://github.com/nixon-voxell/bevy_vello_renderer", rev = "b9fb17a188c302047d7718fb606ba2b0b0ada8c7" }
smallvec = "1.11"
