[package]
name = "motiongfx_core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
motiongfx_core_macros = { path = "macros" }

bevy = "0.13"
bevy_vello = "0.4"
smallvec = "1.11"

[lints]
workspace = true
